title: Tianyang Shen
description: Notes and essays on robotics
author: Tianyang Shen
affiliation:

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
